# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Pages/HTML.gitlab-ci.yml

# Full project: https://gitlab.com/pages/plain-html
build:
  image: node:14.15.3-buster-slim
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - echo "Entrou no Build"
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  dependencies: 
    - build
  script:
    - echo "Entrou no deploy"
    - rm -rf public
    - mv build public    
    - cp public/index.html public/404.html
    - echo "Criando Documentacao..."
    - mkdir .docs
    - cp -r ./docs/* .docs
    - mv .docs public/docs
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH      
